const strings = {
  'appTitle': 'Slajdy',
  'psalm': 'Psalm',
  'acclamation': 'Aklamacja',
  'addLiturgy': 'Dodaj liturgię słowa',
  'removeLiturgy': 'Usuń liturgię słowa',
  'addOrdinary': 'Dodaj części stałe',
  'removeOrdinary': 'Usuń części stałe',
  'addText': 'Dodaj własny tekst',
  'enterText': 'Wpisz tekst',
  'cancel': 'ANULUJ',
  'ok': 'OK',
  'changeDate': 'Zmień datę',
  'remove': 'Usuń',
  'edit': 'Edytuj',
  'verseOrder': 'Zwrotki',
  'emptyTitle': 'Nic tu jeszcze nie ma!',
  'emptyDescription':
      'Aby dodać slajdy, użyj wyszukiwarki\nlub wklej plan jako tekst.',
  'searchSongs': 'Wyszukaj pieśni',
  'editAsText': 'Edytuj jako tekst',
  'menu': 'Pokaż menu',
  'clearText': 'Wyczyść',
  'applyText': 'Wczytaj slajdy',
  'unresolvedOne':
      'Nie udało się jednoznacznie dopasować jednej pieśni. Dotknij ją, aby wybrać odpowiednią.',
  'unresolvedMany':
      'Nie udało się jednoznacznie dopasować {} pieśni. Dotknij je, aby wybrać odpowiednie.',
  'duplicatesRemoved': 'Powtarzające się elementy zostały usunięte z listy.',
  'searchStartTyping': 'Zacznij wpisywać tytuł lub numer pieśni.',
  'searchNoResults': 'Nie znaleziono pasujących pieśni.',
  'itemRemovedSong': 'Usunięto „{}”.',
  'itemRemovedPsalm': 'Usunięto psalm.',
  'itemRemovedAcclamation': 'Usunięto aklamację.',
  'undo': 'COFNIJ',
  'generateSlides': 'Generuj slajdy',
  'slidesOpeningInBrowser': 'Plik ze slajdami zostanie otwarty w przeglądarce.',
  'slidesDownloadedInternal':
      'Plik PDF ze slajdami został pobrany do pamięci telefonu.',
  'move': 'PRZENIEŚ',
  'slidesMoved': 'Plik PDF ze slajdami został przeniesiony.',
  'manual': 'Instrukcja obsługi rzutnika',
  'reloadLyrics': 'Odśwież teksty',
  'newVersionAvailable': 'Nowa wersja jest dostępna',
  'newVersionDescription':
      "Czy chcesz pobrać wersję {latestVersion}? Obecnie masz zainstalowaną {yourVersion}.",
  'download': 'POBIERZ',
  'notNow': 'PÓŹNIEJ',
  'skipVersion': 'POMIŃ',
  'settings': 'Ustawienia',
  'settingsSectionSlides': 'Slajdy',
  'hints': 'Podpowiedzi',
  'enabled': 'Włączone',
  'disabled': 'Wyłączone',
  'fontSize': 'Rozmiar tekstu',
  'aspectRatio': 'Proporcje slajdów',
};
