const strings = {
  'appTitle': 'Slajdy',
  'psalm': 'Psalm',
  'acclamation': 'Aklamacja',
  'addLiturgy': 'Dodaj liturgię słowa',
  'removeLiturgy': 'Usuń liturgię słowa',
  'addOrdinary': 'Dodaj części stałe',
  'removeOrdinary': 'Usuń części stałe',
  'addText': 'Dodaj własny tekst',
  'enterText': 'Wpisz tekst',
  'cancel': 'ANULUJ',
  'ok': 'OK',
  'changeDate': 'Zmień datę',
  'remove': 'Usuń',
  'edit': 'Edytuj',
  'verseOrder': 'Zwrotki',
  'emptyTitle': 'Nic tu jeszcze nie ma!',
  'emptyDescription':
      'Aby dodać slajdy, użyj wyszukiwarki\nlub wklej plan jako tekst.',
  'searchSongs': 'Wyszukaj pieśni',
  'editAsText': 'Edytuj jako tekst',
  'menu': 'Pokaż menu',
  'clearText': 'Wyczyść',
  'applyText': 'Wczytaj slajdy',
  'unresolvedOne':
      'Nie udało się jednoznacznie dopasować jednej pieśni. Dotknij ją, aby wybrać odpowiednią.',
  'unresolvedMany':
      'Nie udało się jednoznacznie dopasować {} pieśni. Dotknij je, aby wybrać odpowiednie.',
  'duplicatesRemoved': 'Powtarzające się elementy zostały usunięte z listy.',
  'searchStartTyping': 'Zacznij wpisywać tytuł lub numer pieśni.',
  'searchNoResults': 'Nie znaleziono pasujących pieśni.',
  'itemRemovedSong': 'Usunięto „{}”.',
  'itemRemovedPsalm': 'Usunięto psalm.',
  'itemRemovedAcclamation': 'Usunięto aklamację.',
  'undo': 'COFNIJ',
  'generateSlides': 'Generuj slajdy',
  'slidesOpeningInBrowser': 'Plik ze slajdami zostanie otwarty w przeglądarce.',
  'move': 'PRZENIEŚ',
  'slidesMoved': 'Plik ze slajdami został zapisany.',
  'manual': 'Instrukcja obsługi rzutnika',
  'reloadLyrics': 'Odśwież teksty',
  'newVersionAvailable': 'Nowa wersja jest dostępna',
  'newVersionDescription':
      "Czy chcesz pobrać wersję {latestVersion}? Obecnie masz zainstalowaną {yourVersion}.",
  'download': 'POBIERZ',
  'notNow': 'PÓŹNIEJ',
  'skipVersion': 'POMIŃ',
  'settings': 'Ustawienia',
  'settingsSectionSlides': 'Slajdy',
  'hints': 'Podpowiedzi',
  'enabled': 'Włączone',
  'disabled': 'Wyłączone',
  'fontSize': 'Rozmiar tekstu',
  'aspectRatio': 'Proporcje slajdów',
  'slidesBehavior': 'Po wygenerowaniu slajdów',
  'behaviorSave': 'Zapisz do pliku',
  'behaviorDisplay': 'Wyświetl',
  'cast': 'Przesyłanie (Chromecast)',
  'castSelectDevice': 'Połącz się z urządzeniem',
  'castNoDevicesFound': 'Nie znaleziono urządzeń.',
  'castError': 'Błąd: {error}',
  'castConnected': 'Połączono z urządzeniem.',
  'castDisconnected': 'Odłączono od urządzenia.',
  'liveSession': 'Pokaz na żywo',
  'liveSessionStarted': 'Pokaz na żywo jest dostępny pod adresem {url}.',
  'shareLink': 'UDOSTĘPNIJ LINK',
  'shareSlides': 'Udostępnij slajdy',
  'saveToFile': 'Zapisz slajdy do pliku',
};
